version: '3.8'

services:
  mysql1:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - 3307:3306
    volumes:
      - db-mysql1:/var/lib/mysql

  mysql2:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - 3308:3306
    volumes:
      - db-mysql2:/var/lib/mysql

  phpmyadmin1:
    image: phpmyadmin/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
     - PMA_HOST=mysql1
    ports:
      - '8080:80'
    depends_on:
      - mysql1
    env_file:
      - .env

  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
     - PMA_HOST=mysql2
    ports:
      - '8081:80'
    depends_on:
      - mysql2
    env_file:
      - .env


volumes:
  db-mysql1:
    driver: local
  db-mysql2:
    driver: local
